[project]
name = "epiverse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest-cov>=6.0.0",
    "pytest>=8.3.3",
    "pyyaml>=6.0.2",
]

[tool.uv.workspace]
members = ["eqlex"]
